services:
  postgres:
    # container_name: database
    image: postgres:latest
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    networks:
      - postgres
  app:
    container_name: backend
    build:
      context: .
      target: development
    restart: on-failure
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydatabase'
    ports:
      - 8080:8080
    depends_on:
      - postgres
    volumes:
      - .:/app:rw
    networks:
      - postgres
networks:
  postgres:
    driver: bridge