services:
  postgres:
    # container_name: database
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - 5432:5432
  app:
    container_name: backend
    build:
      context: .
      target: development
    restart: on-failure
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydatabase'
    ports:
      - 8080:8080
    depends_on:
      - postgres
    volumes:
      - .:/app:rw