
spring:
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
  flyway:
    schemas: public
    driver-class-name: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/mydatabase
    username: postgres
    password: postgres

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days