
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
  flyway:
    schemas: public
    driver-class-name: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/mydatabase
    username: postgres
    password: postgres
