
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
  flyway:
    schemas: public
    driver-class-name: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
